[package]
name = "ped25519"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg16"]
shared = []
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pgrx_test = []

[dependencies]
pgrx = "0.11.4"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8"

[dev-dependencies]
pgrx-tests = "=0.11.4"
